import { useEffect, useState } from "react";

const products = [
  { id: "gac", name: "Dầu Gấc MoaMoa", type: "Dầu ăn dặm", desc: "Nguồn Beta-carotene tự nhiên vượt trội, hỗ trợ thị lực và đề kháng.", price: 189000, oldPrice: 220000, volume: "100ml", image: "/product-gac.png", tags: ["Beta-carotene", "Vitamin A", "Lycopene"], rating: 284, tint: "#FBE9E3" },
  { id: "olive", name: "Dầu Olive Extra Virgin", type: "Dầu ăn dặm", desc: "Nhập khẩu Địa Trung Hải, giàu Omega-9, dịu nhẹ cho hệ tiêu hoá.", price: 245000, oldPrice: 288000, sale: "-15%", volume: "100ml", image: "/product-olive.png", tags: ["Omega-9", "Polyphenols", "Vit E"], rating: 196, tint: "#ECF4E8" },
  { id: "rice", name: "Dầu Gạo Rang Xay", type: "Dầu ăn dặm", desc: "Từ gạo lứt Việt Nam, giàu Vitamin E và Oryzanol tự nhiên.", price: 175000, oldPrice: null, volume: "100ml", image: "/product-rice.png", tags: ["Vitamin E", "Oryzanol", "Sterols"], rating: 312, tint: "#FFF8E2" },
  { id: "avocado", name: "Dầu Bơ MoaMoa", type: "Dầu ăn dặm", desc: "Giàu chất béo lành mạnh, hỗ trợ phát triển trí não và năng lượng.", price: 229000, oldPrice: 265000, sale: "-14%", volume: "100ml", image: "/product-avocado.png", tags: ["Healthy Fats", "Omega", "Êm dịu"], rating: 241, tint: "#EFF6E5" },
  { id: "combo", name: "Combo Phát triển Trí não", type: "Combo khuyên dùng", desc: "Dầu Bơ + Dầu Gạo — bộ đôi vàng cho hành trình phát triển não bộ.", price: 320000, oldPrice: 390000, sale: "-18%", volume: "2×100ml", image: "/combo-brain.png", tags: ["DHA hỗ trợ", "Healthy Fats", "Tổng hợp"], rating: 427, tint: "#EAF4E3", recommended: true },
];

const reviews = [
  ["Dầu Gấc", "Con mình 8 tháng dùng dầu Gấc MoaMoa, da dẻ hồng hào hơn. Mùi thơm nhẹ, trộn cháo là bé ăn hết veo.", "Mẹ Hà Linh", "@halinhmom2024", "🧡"],
  ["Dầu Olive", "Mình thích nhất là bảng thành phần rõ ràng. Chai nhìn sang, nhưng quan trọng là bé dùng hợp bụng.", "Mẹ Thu Hương", "@thuhuong_baby", "💚"],
  ["Combo Trí não", "Combo Bơ + Gạo tiện cực. Sáng nấu cháo bí đỏ thêm vài giọt là thơm, bé nhà mình hợp tác hơn hẳn.", "Mẹ Ngọc Anh", "@ngocanhkitchen", "💛"],
  ["Dầu Gạo", "Mua thử vì bao bì đẹp, dùng rồi mới thấy chất lượng xứng đáng. Không bị mùi hắc như vài loại mình từng mua.", "Mẹ Phương Thảo", "@phuongthao_mom", "💜"],
  ["Dầu Bơ", "Ship nhanh, đóng gói chắc chắn. Dầu Bơ béo nhẹ, mình hay dùng cho nui và cháo cá hồi.", "Mẹ Khánh Vân", "@khanhvan_family", "🧡"],
  ["Dầu Gấc", "Dùng 3 tháng thấy con ăn tốt hơn. Sản phẩm sạch, dễ dùng cho bé từ 6 tháng trở lên.", "Mẹ Minh Tâm", "@minhtam2baby", "💚"],
];

const blogs = [
  { title: "Cách dùng dầu ăn dặm đúng liều", image: "/product-gac.png", excerpt: "Khi nào nên thêm dầu vào cháo, dùng bao nhiêu là đủ và cách giữ trọn dưỡng chất.", content: "Với bé từ 6 tháng tuổi, mẹ có thể bắt đầu bằng 1/2 thìa cà phê dầu ăn dặm cho mỗi bữa cháo hoặc bột, sau đó tăng dần theo khả năng tiêu hoá của bé. Dầu nên được thêm sau khi món ăn đã nấu xong và còn ấm, tránh đun sôi lâu để bảo toàn acid béo và vitamin tự nhiên. Mẹ nên luân phiên các loại dầu như gấc, olive, gạo và bơ để bữa ăn đa dạng dưỡng chất." },
  { title: "Gợi ý thực đơn 6 tháng+", image: "/product-rice.png", excerpt: "Những công thức đơn giản, mềm dịu cho giai đoạn đầu ăn dặm của bé.", content: "Giai đoạn 6 tháng, mẹ nên ưu tiên món mềm, ít gia vị và dễ tiêu hoá như cháo bí đỏ, cháo cà rốt, cháo khoai lang hoặc bột gạo loãng. Sau khi món ăn nguội bớt, thêm vài giọt dầu ăn dặm để hỗ trợ hấp thu vitamin tan trong dầu. Với bé mới bắt đầu, mẹ nên thử từng nguyên liệu riêng trong 2-3 ngày để theo dõi phản ứng của cơ thể bé." },
  { title: "Dầu nào hợp với bé?", image: "/combo-brain.png", excerpt: "Mỗi loại dầu có lợi ích riêng: gấc, olive, gạo và bơ nên dùng thế nào?", content: "Dầu Gấc phù hợp khi mẹ muốn bổ sung beta-carotene tự nhiên. Dầu Olive giàu Omega-9, dịu nhẹ và dễ kết hợp với nhiều món. Dầu Gạo có Vitamin E và Oryzanol, hợp với bữa ăn hằng ngày. Dầu Bơ giàu chất béo lành mạnh, phù hợp cho thực đơn cần năng lượng và hỗ trợ phát triển trí não. Mẹ nên dùng xen kẽ để cân bằng dưỡng chất." },
];

function money(n) { return n.toLocaleString("vi-VN") + "đ"; }
function LeafLogo({ small = false }) { return <img src="/leaf-logo.png" alt="MoaMoa leaf" className={small ? "h-4 w-4 object-contain" : "h-8 w-8 object-contain"} />; }
function UserIcon() { return <svg viewBox="0 0 24 24" className="h-7 w-7" fill="none"><circle cx="12" cy="8" r="4" stroke="#4A5D23" strokeWidth="1.8"/><path d="M4.5 21c1.4-4.3 4-6.2 7.5-6.2s6.1 1.9 7.5 6.2" stroke="#4A5D23" strokeWidth="1.8" strokeLinecap="round"/></svg>; }
function SearchIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none"><circle cx="11" cy="11" r="7" stroke="#111" strokeWidth="2"/><path d="M16.5 16.5L21 21" stroke="#111" strokeWidth="2" strokeLinecap="round"/></svg>; }
function PayIcon({ label }) { return <div className="grid h-9 min-w-14 place-items-center rounded-lg border border-[#D8D0C2] bg-white/70 px-3 text-xs font-black text-[#132508] transition hover:scale-110 hover:bg-white">{label}</div>; }
function Social({ children }) { return <div className="group relative grid h-11 w-11 cursor-pointer place-items-center rounded-full bg-white/10 text-xl transition hover:scale-110 hover:bg-white/20"><span>{children}</span><span className="pointer-events-none absolute -top-9 rounded-md bg-white px-2 py-1 text-xs font-bold text-[#132508] opacity-0 shadow-lg transition group-hover:opacity-100">MoaMoa</span></div>; }
function UserBadge({ initial }) { return <div className="grid h-7 w-7 place-items-center rounded-full bg-[#4A5D23] text-sm font-black uppercase text-white">{initial}</div>; }

function ProductCard({ product, onAdd, onBuy }) {
  return (
    <article className={`group relative overflow-hidden rounded-[24px] border bg-white shadow-[0_18px_50px_rgba(62,59,46,0.08)] transition duration-300 hover:-translate-y-2 hover:shadow-[0_26px_70px_rgba(74,93,35,0.18)] ${product.recommended ? "border-[#4A5D23]" : "border-[#E6DED2]"}`}>
      <div className="relative flex h-[285px] items-center justify-center overflow-hidden" style={{ background: product.tint }}>
        {product.recommended && <div className="absolute left-4 top-4 z-10 rounded-full bg-[#4A5D23] px-4 py-2 text-xs font-bold uppercase tracking-wider text-white">★ Khuyên dùng</div>}
        {product.sale && <div className="absolute right-4 top-4 z-10 rounded-full bg-[#C04A3B] px-4 py-2 text-xs font-bold text-white">{product.sale}</div>}
        <img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-110" />
        <span className="absolute bottom-5 rounded-full bg-white/90 px-4 py-1 text-xs text-[#777] shadow-sm">{product.volume}</span>
      </div>
      <div className="p-6">
        <p className="mb-3 text-[11px] font-extrabold uppercase tracking-[5px] text-[#4A5D23]">{product.type}</p>
        <h3 className="min-h-[58px] font-serif text-[25px] font-bold leading-tight text-[#2D2D2D]">{product.name}</h3>
        <p className="mt-3 min-h-[74px] text-sm leading-7 text-[#666]">{product.desc}</p>
        <div className="mt-5 flex flex-wrap gap-2">{product.tags.map((tag) => <span key={tag} className="rounded-full border border-[#CAD6B3] bg-[#EEF3DF] px-3 py-1 text-xs font-bold text-[#4A5D23]">{tag}</span>)}</div>
        <div className="mt-5 flex items-center gap-2 text-sm text-[#F2BE4B]">★★★★★ <span className="text-[#777]">({product.rating})</span></div>
        <div className="mt-5"><p className="font-serif text-2xl font-bold text-[#2D2D2D]">{money(product.price)}</p>{product.oldPrice && <p className="text-sm text-gray-400 line-through">{money(product.oldPrice)}</p>}</div>
        <div className="mt-5 flex justify-center gap-2">
          <button onClick={() => onAdd(product)} className="whitespace-nowrap rounded-[14px] border border-[#C04A3B] bg-white px-3.5 py-2 text-[12px] font-bold leading-none text-[#C04A3B] transition hover:scale-105 hover:bg-[#FFF3F0]">+ Thêm vào giỏ</button>
          <button onClick={() => onBuy(product)} className="whitespace-nowrap rounded-[14px] bg-[#C04A3B] px-4 py-2 text-[12px] font-bold leading-none text-white shadow-lg shadow-[#C04A3B]/20 transition hover:scale-105 hover:bg-[#A93F33]">Mua ngay</button>
        </div>
      </div>
    </article>
  );
}

export default function App() {
  const [cart, setCart] = useState([]);
  const [showLogin, setShowLogin] = useState(false);
  const [showCart, setShowCart] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [showCheckout, setShowCheckout] = useState(false);
  const [query, setQuery] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userInitial, setUserInitial] = useState("");
  const [activeBlog, setActiveBlog] = useState(null);
  const [pendingBlog, setPendingBlog] = useState(null);

  useEffect(() => {
    const saved = localStorage.getItem("moamoaUser");
    if (saved) {
      const data = JSON.parse(saved);
      setIsLoggedIn(true);
      setUserInitial(data.initial || "M");
    }
  }, []);

  const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0);
  const count = cart.reduce((s, i) => s + i.qty, 0);
  const addToCart = (item) => { setCart((prev) => { const existed = prev.find((p) => p.id === item.id); return existed ? prev.map((p) => p.id === item.id ? { ...p, qty: p.qty + 1 } : p) : [...prev, { ...item, qty: 1 }]; }); setShowCart(true); };
  const updateQty = (id, delta) => setCart((prev) => prev.map((p) => p.id === id ? { ...p, qty: Math.max(1, p.qty + delta) } : p));
  const removeItem = (id) => setCart((prev) => prev.filter((p) => p.id !== id));
  const buyNow = (item) => { setCart([{ ...item, qty: 1 }]); setShowCheckout(true); };
  const openBlog = (blog) => { if (!isLoggedIn) { setPendingBlog(blog); setShowLogin(true); return; } setActiveBlog(blog); };
  const handleAuth = (e) => { e.preventDefault(); const form = new FormData(e.currentTarget); const email = String(form.get("email") || ""); const pass = String(form.get("password") || ""); const raw = (email.trim() || pass.trim()); if (raw) { const initial = raw.charAt(0).toUpperCase(); localStorage.setItem("moamoaUser", JSON.stringify({ email, initial })); setIsLoggedIn(true); setUserInitial(initial); setShowLogin(false); if (pendingBlog) { setActiveBlog(pendingBlog); setPendingBlog(null); } } };
  const handleSearch = (e) => { const value = e.target.value; setQuery(value); const text = value.toLowerCase(); if (!text.trim()) return; if (text.includes("gấc") || text.includes("olive") || text.includes("gạo") || text.includes("bơ") || text.includes("sản phẩm")) document.getElementById("products")?.scrollIntoView({ behavior: "smooth" }); else if (text.includes("chuyên gia")) document.getElementById("expert")?.scrollIntoView({ behavior: "smooth" }); else if (text.includes("mẹ") || text.includes("review")) document.getElementById("reviews")?.scrollIntoView({ behavior: "smooth" }); else if (text.includes("cẩm nang") || text.includes("blog")) document.getElementById("blog")?.scrollIntoView({ behavior: "smooth" }); else if (text.includes("câu chuyện") || text.includes("mộc hoa")) document.getElementById("story")?.scrollIntoView({ behavior: "smooth" }); };

  return (
    <div className="min-h-screen bg-[#F8F5F0] text-[#2D2D2D]">
      <div className="bg-[#4A5D23] py-3 text-center text-sm font-semibold tracking-wide text-white">Dầu ăn dặm cao cấp từ nguồn nguyên liệu đạt chuẩn · Nuôi dưỡng hành trình lớn khôn của bé bằng dưỡng chất tự nhiên</div>

      <nav className="sticky top-0 z-50 flex items-center justify-between border-b border-[#E5DED2] bg-[#F8F5F0]/95 px-10 py-5 backdrop-blur-xl">
        <div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#6B7D2C]"><LeafLogo /></div><div><h1 className="font-serif text-4xl font-bold leading-none">MoaMoa</h1><p className="mt-1 text-[10px] uppercase tracking-[5px] text-[#6B7D2C]">Pure · Natural · Vietnamese</p></div></div>
        <div className="hidden gap-12 text-center lg:flex">{[["#story","Câu chuyện","Story"],["#products","Sản phẩm","Product"],["#expert","Chuyên gia","Experts"],["#reviews","Mẹ tin dùng","Reviews"],["#blog","Cẩm nang","Blog"]].map((i)=><a key={i[1]} href={i[0]} className="font-semibold hover:text-[#4A5D23]"><span className="text-[16px]">{i[1]}</span><p className="text-sm text-gray-400">{i[2]}</p></a>)}</div>
        <div className="flex items-center gap-4">{showSearch ? <input autoFocus value={query} onChange={handleSearch} onBlur={()=>!query&&setShowSearch(false)} placeholder="Tìm sản phẩm..." className="w-64 rounded-full border border-[#DDD4C8] bg-white px-5 py-3 outline-none"/> : <button onClick={()=>setShowSearch(true)} className="transition hover:scale-110"><SearchIcon /></button>}<button onClick={()=>setShowLogin(true)} className="flex h-11 w-11 items-center justify-center rounded-full border border-[#D8D0C2] bg-[#F8F5F0] transition hover:scale-110">{isLoggedIn ? <UserBadge initial={userInitial} /> : <UserIcon />}</button><button onClick={()=>setShowCart(true)} className="relative text-3xl transition hover:scale-110">🛒<span className="absolute -right-3 -top-3 flex h-6 w-6 items-center justify-center rounded-full bg-[#C04A3B] text-xs font-bold text-white">{count}</span></button></div>
      </nav>

      <section className="grid items-center gap-16 px-16 py-24 lg:grid-cols-2">
        <div><div className="mb-10 inline-flex items-center gap-3 rounded-full border border-[#B8C09B] bg-[#F4F1E8] px-8 py-4 text-sm font-bold uppercase tracking-[4px] text-[#4A5D23] shadow-sm"><LeafLogo small />100% Tự nhiên · Đạt chuẩn VietGAP</div><h1 className="max-w-[720px] font-serif text-[64px] font-semibold leading-[1.05] tracking-[-1px] text-[#2D2D2D]">Mẹ chọn điều lành,<br/><span className="font-semibold italic text-[#4A5D23]">con lớn khôn</span><br/>vững vàng</h1><p className="mt-9 max-w-[760px] text-2xl leading-10 text-[#555]">Từ <i>quả gấc, olive, gạo đến bơ</i> – mỗi giọt dầu đều được chọn lọc để đồng hành cùng hành trình phát triển của trẻ nhỏ.<span className="italic text-[#B64638]"> The chef's kiss</span> for your baby.</p><div className="mt-10 flex flex-wrap gap-6"><a href="#products" className="rounded-full bg-[#4A5D23] px-10 py-5 text-xl font-bold text-white shadow-lg transition hover:scale-105">Khám phá sản phẩm</a><a href="#story" className="rounded-full border border-[#4A5D23] bg-white px-10 py-5 text-xl font-bold text-[#4A5D23] transition hover:scale-105">Câu chuyện Mộc Hoa</a></div><div className="mt-12 flex flex-wrap gap-5 text-[#4A5D23]"><div className="rounded-full bg-[#F3F1E7] px-7 py-4 shadow-sm">🛡️ Kiểm định VSATTP</div><div className="rounded-full bg-[#F3F1E7] px-7 py-4 shadow-sm">🏆 Giải thưởng 2024</div><div className="rounded-full bg-[#F3F1E7] px-7 py-4 shadow-sm">👶 Từ 6 tháng tuổi</div></div></div>
        <img src="/oil-hero.png" alt="MoaMoa oils" className="w-full rounded-[45px] shadow-2xl transition duration-500 hover:scale-[1.02]" />
      </section>

      <section id="story" className="bg-[#F8F5F0] px-16 py-24"><div className="grid items-center gap-16 lg:grid-cols-2"><div><div className="mb-6 flex items-center gap-4"><span className="h-px w-16 bg-[#4A5D23]"/><p className="text-sm font-bold uppercase tracking-[5px] text-[#4A5D23]">Từ Mộc Hoa đến MoaMoa</p><span className="h-px w-16 bg-[#4A5D23]"/></div><h2 className="font-serif text-6xl font-bold leading-[1.05] text-[#2D2D2D]">Tên thương hiệu mang<br/><span className="italic text-[#4A5D23]">tiếng hôn của mẹ</span></h2><div className="mt-10 space-y-7 text-lg leading-9 text-[#666]"><p><b className="text-[#2D2D2D]">“MoaMoa”</b> — âm thanh của nụ hôn mẹ trao con mỗi sáng. Tiếng cười của bé khi thưởng thức bữa ăn dặm đầu tiên. Một cái tên đơn giản nhưng chứa đựng cả một thế giới yêu thương.</p><p>Chúng tôi cam kết hiện đại hóa làng nông nghiệp truyền thống Việt Nam — kết nối trực tiếp từ vùng nguyên liệu đạt chuẩn đến bàn ăn của các gia đình. Mỗi chai dầu là một hành trình từ đất Việt.</p></div><div className="mt-10 space-y-5">{[["🌿","Canh tác tự nhiên","Không thuốc trừ sâu, không chất bảo quản"],["⚗️","Công nghệ ép lạnh","Giữ trọn dưỡng chất thiết yếu"],["🛡️","Kiểm định độc lập","Đạt tiêu chuẩn FDA & VSATTP"]].map((item)=><div key={item[1]} className="flex items-center gap-5 rounded-2xl border border-[#DDD7C8] bg-[#F3F1E7] px-7 py-5 shadow-sm"><div className="text-2xl text-[#4A5D23]">{item[0]}</div><div><h3 className="font-bold text-[#2D2D2D]">{item[1]}</h3><p className="text-[#777]">{item[2]}</p></div></div>)}</div></div><div className="relative"><div className="overflow-hidden rounded-[38px] shadow-2xl"><img src="/nong-san-viet.png" alt="Quảng bá nông sản Việt" className="h-[560px] w-full object-cover"/></div><div className="absolute right-[-20px] top-[-25px] rounded-3xl bg-white/95 p-6 shadow-xl"><p className="font-serif text-3xl font-bold text-[#4A5D23]">12+</p><p className="text-sm text-[#777]">Vùng nông sản<br/>đối tác</p></div><div className="absolute bottom-[-25px] left-[-25px] rounded-3xl bg-white/95 p-6 shadow-xl"><p className="font-serif text-3xl font-bold text-[#C04A3B]">50K+</p><p className="text-sm text-[#777]">Gia đình tin<br/>yêu MoaMoa</p></div></div></div></section>

      <section id="products" className="bg-[#F1EDE4] px-10 py-24"><div className="mb-14 text-center"><div className="mb-3 flex items-center justify-center gap-4"><span className="h-px w-14 bg-[#4A5D23]"/><p className="text-xs font-bold uppercase tracking-[5px] text-[#4A5D23]">The Collection</p><span className="h-px w-14 bg-[#4A5D23]"/></div><h2 className="font-serif text-5xl font-bold">Bộ sưu tập Dầu Ăn Dặm</h2><p className="mx-auto mt-4 max-w-xl text-[#777]">Mỗi sản phẩm là một cam kết — từ vùng nguyên liệu đạt chuẩn đến dưỡng chất tốt nhất cho con yêu của bạn.</p></div><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2 xl:grid-cols-5">{products.map((p)=><ProductCard key={p.id} product={p} onAdd={addToCart} onBuy={buyNow}/>)}</div><div className="mt-12 text-center"><button className="rounded-full border border-[#4A5D23] px-10 py-4 font-bold text-[#4A5D23] transition hover:scale-105">Xem toàn bộ sản phẩm →</button></div></section>

      <section id="expert" className="bg-[#EEF3DF] px-16 py-24"><div className="mb-10 text-center"><div className="mb-3 flex items-center justify-center gap-4"><span className="h-px w-14 bg-[#4A5D23]"/><p className="text-xs font-bold uppercase tracking-[5px] text-[#4A5D23]">Được chuyên gia xác nhận</p><span className="h-px w-14 bg-[#4A5D23]"/></div><h2 className="font-serif text-6xl font-bold leading-tight">Tin tưởng bởi các<br/><span className="italic text-[#4A5D23]">chuyên gia dinh dưỡng</span></h2><p className="mx-auto mt-5 max-w-3xl text-xl leading-8 text-[#666]">Được nghiên cứu, phân tích và khuyến nghị bởi bác sĩ nhi khoa và chuyên gia dinh dưỡng hàng đầu Việt Nam.</p></div><div className="mx-auto max-w-5xl rounded-[38px] bg-white p-12 shadow-2xl"><p className="font-serif text-3xl italic leading-relaxed text-[#555]">“Dầu ăn dặm đóng vai trò then chốt trong 1000 ngày đầu đời. Tôi đặc biệt đánh giá cao MoaMoa ở khả năng bảo toàn acid béo thiết yếu qua công nghệ ép lạnh.”</p><div className="mt-8 flex items-center justify-between"><div><p className="text-xl font-bold">TS. BS. Nguyễn Thị Minh Ngọc</p><p className="text-[#4A5D23]">Chuyên gia Dinh dưỡng Nhi khoa · BV Nhi Trung ương</p></div><p className="text-yellow-400">★★★★★</p></div></div></section>

      <section id="reviews" className="bg-[#EEF5E8] px-16 py-24"><div className="mb-14 text-center"><div className="mb-3 flex items-center justify-center gap-4"><span className="h-px w-14 bg-[#4A5D23]"/><p className="text-xs font-bold uppercase tracking-[5px] text-[#4A5D23]">Mẹ thông thái tin dùng</p><span className="h-px w-14 bg-[#4A5D23]"/></div><h2 className="font-serif text-6xl font-bold">Hơn 50,000 mẹ đã chọn MoaMoa</h2></div><div className="grid gap-7 md:grid-cols-2 xl:grid-cols-3">{reviews.map((r)=><div key={r[2]} className="rounded-[28px] bg-white p-7 shadow-sm"><span className="rounded-full border border-[#F4C8C1] bg-[#FFF1EE] px-4 py-2 text-xs font-bold text-[#C04A3B]">{r[0]}</span><p className="mt-5 text-yellow-400">★★★★★</p><p className="mt-4 min-h-[96px] leading-8 text-[#666]">{r[1]}</p><div className="mt-6 flex items-center justify-between"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#EEF3DF]">{r[4]}</div><div><p className="font-bold">{r[2]}</p><p className="text-sm text-[#6B7D2C]">{r[3]}</p></div></div><span className="rounded-full bg-[#EEF3DF] px-4 py-2 text-xs font-bold text-[#4A5D23]">✓ Đã mua</span></div></div>)}</div></section>

      <section id="blog" className="px-16 py-24"><div className="mb-14 text-center"><h2 className="font-serif text-6xl font-bold">Cẩm nang ăn dặm</h2><p className="mx-auto mt-5 max-w-3xl text-xl leading-8 text-[#666]"><b>Nhận cẩm nang ăn dặm từ chuyên gia.</b> Hướng dẫn ăn dặm theo từng giai đoạn, công thức nấu ăn cho bé, và ưu đãi độc quyền dành riêng cho thành viên.</p></div><div className="grid gap-9 md:grid-cols-3">{blogs.map((b)=><button key={b.title} onClick={()=>openBlog(b)} className="rounded-[32px] bg-white p-8 text-left shadow-sm transition hover:-translate-y-2 hover:shadow-2xl"><div className="mb-7 h-56 overflow-hidden rounded-[28px]"><img src={b.image} className="h-full w-full object-cover transition duration-700 hover:scale-110"/></div><h3 className="font-serif text-4xl font-bold">{b.title}</h3><p className="mt-5 text-lg leading-8 text-[#666]">{b.excerpt}</p><p className="mt-6 font-bold text-[#4A5D23]">Đọc cẩm nang →</p></button>)}</div></section>

      <footer className="bg-[#132508] px-16 py-20 text-white"><div className="grid gap-16 md:grid-cols-4"><div><div className="mb-6 flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#6B7D2C]"><LeafLogo small/></div><h2 className="font-serif text-4xl font-bold">MoaMoa</h2></div><p className="leading-8 text-white/60">Dầu ăn dặm cao cấp 100% tự nhiên từ nguồn nông sản Việt đạt chuẩn. Vì mỗi bữa ăn của con là một điều thiêng liêng.</p><div className="mt-10"><h3 className="mb-4 font-bold uppercase tracking-[3px]">Theo dõi chúng tôi</h3><div className="flex gap-3"><Social>◎</Social><Social>f</Social><Social>♪</Social></div></div></div><div><h3 className="mb-6 font-bold uppercase tracking-[4px]">Sản phẩm</h3><div className="space-y-4 text-white/60 [&_p]:cursor-pointer [&_p]:transition [&_p]:duration-200 [&_p:hover]:translate-x-1 [&_p:hover]:scale-[1.03] [&_p:hover]:text-white"><p>Dầu Gấc nguyên chất</p><p>Dầu Olive cho bé</p><p>Dầu Gạo ăn dặm</p><p>Dầu Bơ hữu cơ</p><p>Combo tiết kiệm</p></div></div><div><h3 className="mb-6 font-bold uppercase tracking-[4px]">Thông tin</h3><div className="space-y-4 text-white/60 [&_p]:cursor-pointer [&_p]:transition [&_p]:duration-200 [&_p:hover]:translate-x-1 [&_p:hover]:scale-[1.03] [&_p:hover]:text-white"><p>Câu chuyện MoaMoa</p><p>Chuyên gia dinh dưỡng</p><p>Cẩm nang ăn dặm</p><p>Vùng nguyên liệu</p><p>Chứng nhận chất lượng</p></div></div><div><h3 className="mb-6 font-bold uppercase tracking-[4px]">Phương thức thanh toán</h3><div className="flex flex-wrap gap-3"><PayIcon label="VISA"/><PayIcon label="MC"/><PayIcon label="JCB"/><PayIcon label="MoMo"/></div><h3 className="mb-4 mt-10 font-bold uppercase tracking-[4px]">Hỗ trợ</h3><div className="space-y-3 text-white/60 [&_p]:cursor-pointer [&_p]:transition [&_p]:duration-200 [&_p:hover]:translate-x-1 [&_p:hover]:scale-[1.03] [&_p:hover]:text-white"><p>Chính sách đổi trả</p><p>Điều khoản sử dụng</p><p>Chính sách bảo mật</p></div></div></div><div className="mt-16 border-t border-white/10 pt-8 text-white/40">© 2026 MoaMoa. All rights reserved.</div></footer>

      {showLogin && <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/40"><form onSubmit={handleAuth} className="relative w-[430px] rounded-[30px] bg-white p-10"><button type="button" onClick={()=>setShowLogin(false)} className="absolute right-6 top-5 text-3xl">×</button><h2 className="text-center text-3xl font-bold">ĐĂNG NHẬP TÀI KHOẢN</h2><p className="mb-6 mt-2 border-b border-[#2D2D2D] pb-4 text-center text-gray-500">Nhập email và mật khẩu của bạn:</p><input name="email" placeholder="Email" className="mb-4 w-full border border-[#d8d3c8] bg-white px-4 py-4 outline-none"/><input name="password" type="password" placeholder="Mật khẩu" className="mb-4 w-full border border-[#d8d3c8] bg-white px-4 py-4 outline-none"/><p className="mb-5 text-[13px] leading-5 text-[#8b8b8b]">This site is protected by reCAPTCHA and the Google <span className="text-[#3b82f6]">Privacy Policy</span> and <span className="text-[#3b82f6]">Terms of Service</span> apply.</p><button className="w-full rounded-full bg-[#1d1d22] py-4 text-sm font-bold tracking-wide text-white">ĐĂNG NHẬP</button><div className="mt-8 space-y-1 text-[15px] text-[#555]"><p>Khách hàng mới? <span className="font-medium">Tạo tài khoản</span></p><p>Quên mật khẩu? Khôi phục mật khẩu</p></div></form></div>}
      {showCheckout && <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/40"><div className="relative w-[520px] rounded-[32px] bg-white p-10 shadow-2xl"><button onClick={()=>setShowCheckout(false)} className="absolute right-6 top-5 text-3xl">×</button><h2 className="font-serif text-4xl font-bold">Thanh toán COD</h2><p className="mt-2 text-[#666]">Nhập thông tin để MoaMoa xác nhận đơn hàng.</p><div className="mt-8 space-y-4"><input placeholder="Họ và tên" className="w-full rounded-xl border p-4"/><input placeholder="Số điện thoại" className="w-full rounded-xl border p-4"/><input placeholder="Địa chỉ nhận hàng" className="w-full rounded-xl border p-4"/><textarea placeholder="Ghi chú cho MoaMoa" className="h-28 w-full rounded-xl border p-4"/></div><div className="mt-6 rounded-2xl bg-[#F3F1E7] p-5"><div className="flex justify-between font-bold"><span>Tổng thanh toán</span><span>{money(total)}</span></div></div><button className="mt-6 w-full rounded-full bg-[#4A5D23] py-4 font-bold text-white transition hover:scale-105">Xác nhận đặt hàng</button></div></div>}
      {activeBlog && <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/40"><div className="relative max-h-[85vh] w-[760px] overflow-y-auto rounded-[32px] bg-white p-10 shadow-2xl"><button onClick={()=>setActiveBlog(null)} className="absolute right-6 top-5 text-3xl">×</button><img src={activeBlog.image} className="mb-8 h-72 w-full rounded-[28px] object-cover"/><h2 className="font-serif text-5xl font-bold">{activeBlog.title}</h2><p className="mt-6 text-xl leading-9 text-[#555]">{activeBlog.content}</p></div></div>}
      {showCart && <div className="fixed inset-0 z-[998] bg-black/30" onClick={()=>setShowCart(false)}><aside onClick={(e)=>e.stopPropagation()} className="fixed right-0 top-0 h-full w-[520px] overflow-y-auto bg-white p-7 shadow-2xl"><div className="mb-6 flex items-center justify-between border-b pb-5"><h3 className="text-2xl font-bold">Giỏ hàng của bạn</h3><div className="flex items-center gap-4"><span>{count} sản phẩm</span><button onClick={()=>setShowCart(false)} className="text-3xl">×</button></div></div>{cart.length===0?<p className="text-gray-500">Giỏ hàng đang trống.</p>:<><div className="space-y-5">{cart.map((item)=><div key={item.id} className="flex gap-4 border-b pb-5"><img src={item.image} className="h-28 w-24 rounded-xl object-cover"/><div className="flex-1"><div className="flex justify-between gap-3"><h4 className="font-bold uppercase">{item.name}</h4><button onClick={()=>removeItem(item.id)} className="text-xl">×</button></div><p className="mt-2 text-sm text-gray-500">{money(item.price)}</p><div className="mt-3 flex w-fit items-center overflow-hidden rounded-lg border"><button onClick={()=>updateQty(item.id,-1)} className="px-4 py-2">−</button><span className="bg-[#F3F1E7] px-4 py-2">{item.qty}</span><button onClick={()=>updateQty(item.id,1)} className="px-4 py-2">+</button></div></div></div>)}</div><div className="mt-8 rounded-[24px] bg-[#F8F5F0] p-5"><div className="flex justify-between text-lg"><span>Tổng tiền thanh toán:</span><b>{money(total)}</b></div></div><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setShowCart(false)} className="rounded-xl border border-[#222] py-4 font-bold">TIẾP TỤC MUA HÀNG</button><button onClick={()=>setShowCheckout(true)} className="rounded-xl bg-[#1d1d22] py-4 font-bold text-white">GIỎ HÀNG</button></div></>}</aside></div>}
    </div>
  );
}
